routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::prefix('/admin')->group(function () {
    Route::group(['middleware' => ['auth', 'admin']], function () {
        Route::view('/dashboard','backend.index')->name('admin.dashboard');
        Route::resource('/roles', App\Http\Controllers\Backend\RolesController::class);
        Route::resource('/users', App\Http\Controllers\Backend\UsersController::class);
        Route::resource('/settings', App\Http\Controllers\Backend\ConfigsController::class);
        Route::post('users/{id}/update-password', [App\Http\Controllers\Backend\UsersController::class, 'updatePassword'])->name('update.password');
       
        Route::prefix('/master')->group(function () {
            Route::resource('/categories', App\Http\Controllers\Backend\MasterCategoryController::class);
            Route::resource('/country-codes', App\Http\Controllers\Backend\MasterCountryCodeController::class);
            Route::resource('/current-jobs', App\Http\Controllers\Backend\MasterCurrentJobController::class);
            Route::resource('/experiences', App\Http\Controllers\Backend\MasterExperiencesController::class);
            Route::resource('/languages', App\Http\Controllers\Backend\MasterLanguageController::class);
            Route::resource('/levels', App\Http\Controllers\Backend\MasterLevelController::class);
            Route::resource('/locations', App\Http\Controllers\Backend\MasterLocationController::class);
            Route::resource('/nationalities', App\Http\Controllers\Backend\MasterNationalitiesController::class);
            Route::resource('/qualifications', App\Http\Controllers\Backend\MasterQualificationsController::class);
            Route::resource('/salary-ranges', App\Http\Controllers\Backend\MasterSalaryRangeController::class);
            Route::resource('/sectors', App\Http\Controllers\Backend\MasterSectorController::class);
            Route::resource('/types', App\Http\Controllers\Backend\MasterTypeController::class);
        });

        Route::prefix('/settings')->group(function () {
            Route::post('/mail', [App\Http\Controllers\Backend\ConfigsController::class, 'mail'])->name('settings.mail');
        });
    });
});

Route::prefix('jobseeker')->group(function () {
    Route::group(['middleware' => ['auth', 'jobseeker']], function () {
        Route::view('/dashboard','jobseekers.index')->name('jobseeker.dashboard');

        Route::prefix('my-profile')->group(function () {
            //view
            Route::get('/basic-information', [App\Http\Controllers\ProfileJobSeekerController::class, 'basic_information_view'])->name('my-profile.basic-information');   
            Route::get('/introduction', [App\Http\Controllers\ProfileJobSeekerController::class, 'introduction_view'])->name('my-profile.introduction');   
            Route::get('/qualifications', [App\Http\Controllers\ProfileJobSeekerController::class, 'qualifications_view'])->name('my-profile.qualifications');
            Route::get('/work-history', [App\Http\Controllers\ProfileJobSeekerController::class, 'work_history_view'])->name('my-profile.work-history');
            Route::get('/skills', [App\Http\Controllers\ProfileJobSeekerController::class, 'skills_view'])->name('my-profile.skills');
            Route::get('/languages', [App\Http\Controllers\ProfileJobSeekerController::class, 'languages_view'])->name('my-profile.languages');
            Route::get('/resume', [App\Http\Controllers\ProfileJobSeekerController::class, 'resume_view'])->name('my-profile.resume');
            Route::get('/preferences', [App\Http\Controllers\ProfileJobSeekerController::class, 'preferences_view'])->name('my-profile.preferences');
            
            //
            Route::post('/introduction/update/{id}', [App\Http\Controllers\ProfileJobSeekerController::class, 'introduction_post'])->name('my-profile.introduction-post');
            Route::post('/qualifications-post', [App\Http\Controllers\ProfileJobSeekerController::class, 'qualifications_post'])->name('my-profile.qualifications-post');
            Route::delete('/qualifications-{id}', [App\Http\Controllers\ProfileJobSeekerController::class, 'qualifications_delete'])->name('my-profile.qualifications-delete');
            Route::post('/experience-post', [App\Http\Controllers\ProfileJobSeekerController::class, 'work_history_post'])->name('my-profile.experience-post');
            Route::delete('/experience-{id}', [App\Http\Controllers\ProfileJobSeekerController::class, 'work_history_delete'])->name('my-profile.experience-delete');
            Route::post('/skill-post', [App\Http\Controllers\ProfileJobSeekerController::class, 'skill_post'])->name('my-profile.skill-post');
            Route::post('/skill-update/{id}', [App\Http\Controllers\ProfileJobSeekerController::class, 'skill_update'])->name('my-profile.skill-update');
            Route::delete('/skill-{id}', [App\Http\Controllers\ProfileJobSeekerController::class, 'skill_delete'])->name('my-profile.skill-delete');
            Route::post('/language-post', [App\Http\Controllers\ProfileJobSeekerController::class, 'language_post'])->name('my-profile.language-post');
            Route::delete('/language-{id}', [App\Http\Controllers\ProfileJobSeekerController::class, 'language_delete'])->name('my-profile.language-delete');
            //id -- ganti auth
            Route::post('/basic-information/update/{id}', [App\Http\Controllers\ProfileJobSeekerController::class, 'basic_information_update'])->name('update.basic-information');
            Route::post('/preferences/update/{id}', [App\Http\Controllers\ProfileJobSeekerController::class, 'preferences_update'])->name('update.preferences');
        });
    });
});

Route::prefix('employer')->group(function () {
    Route::group(['middleware' => ['auth', 'employer']], function () {
        Route::view('/dashboard','employer.index')->name('employer.dashboard');
    });
});
Route::group(['middleware' => ['auth']], function () {
    Route::prefix('security')->group(function () {
        //view
        Route::get('/change-password', [App\Http\Controllers\ProfileJobSeekerController::class, 'change_password_view'])->name('security.change-password'); 
        Route::get('/hide-password', [App\Http\Controllers\ProfileJobSeekerController::class, 'hide_password_view'])->name('security.hide-password');    
        //post
        Route::post('/post-change-password', [App\Http\Controllers\ProfileJobSeekerController::class, 'change_password_post'])->name('security.change-password-post'); 
        Route::post('/post-hide-password', [App\Http\Controllers\ProfileJobSeekerController::class, 'hide_password_post'])->name('security.hide-password-post');    
        //
        Route::get('/basic-company-information', [App\Http\Controllers\CompaniesController::class, 'basic_company_information_view'])->name('company-profile.basic-information');   
        Route::post('/basic-information/update/{id}', [App\Http\Controllers\CompaniesController::class, 'basic_company_information_update'])->name('update-company.basic-information');
        Route::get('/sub-company', [App\Http\Controllers\CompaniesController::class, 'index_sub_company'])->name('sub-company.index');
        
    });
});

app/Http/Controllers/Backend/ConfigsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Configs;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;


class ConfigsController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:settings-view', ['only' => ['index']]); 
    }
    public function index()
    {
        return view('backend.settings.index');
    }
    public function store(Request $request)
    {
      
        $rules =array(
            'name' => 'required',
            'url' => 'required|url',
            'description' => 'required',
            'logo' => 'required',
            'favicon' => 'required',// |dimensions:max_width=32px,max_height=32',
        );

        $validator=Validator::make($request->all(),$rules);
        
        if($validator->fails())
        {
            $messages=$validator->messages();
            $errors=$messages->all();
            return response()->json(["status"=>"error","message"=>$errors[0]], 200);
        }
       
        if ($request->hasFile('logo')) {
            $image = $request->file('logo');
			$imagename = $image->getClientOriginalName();
			$a = explode(".", $imagename);
			$fileExt = strtolower(end($a));  
            $namaFile = substr(md5(date("YmdHis")),0,10).".".$fileExt;
            $destination_path= public_path().'/image/';
			$request->file('logo')->move($destination_path,$namaFile);
        }else{
            $namaFile = config('mail.from.app_logo');
        }

        if ($request->file('favicon')) {

            $imageFavicon = $request->file('favicon');
			$imagenameFavicon = $imageFavicon->getClientOriginalName();
			$aFavicon = explode(".", $imagenameFavicon);
			$fileExtFavicon = strtolower(end($aFavicon));  
            $namaFileFavicon = substr(md5(date("YmdHis")),0,10).".".$fileExtFavicon;
            $destination_pathFavicon = public_path().'/image/';
			$request->file('favicon')->move($destination_pathFavicon,$namaFileFavicon);
    
        }else{
            $namaFileFavicon = config('mail.from.app_favicon');
        }
       
     
        Configs::where('key','app.name')->update(['value' => $request->name]);
        Configs::where('key','app.url')->update(['value' => $request->url]);
        Configs::where('key','mail.from.app_description')->update(['value' => $request->description]);
        Configs::where('key','mail.from.app_logo')->update(['value' => $namaFile]);
        Configs::where('key','mail.from.app_favicon')->update(['value' => $namaFileFavicon]);

        return response()->json(["status"=>"success","message"=>'Update was successful!'], 200);
    }

    public function mail(Request $request){

        $rules =array(
            'mail_name' => 'required',
            'mail_address' => 'required',
            'mail_driver' => 'required',
            'mail_host' => 'required',
            'mail_port' => 'required',
            'mail_username' => 'required',
            'mail_password' => 'required',
            'mail_encryption' => 'required'
        );

        $validator=Validator::make($request->all(),$rules);
        
        if($validator->fails())
        {
            $messages=$validator->messages();
            $errors=$messages->all();
            return response()->json(["status"=>"error","message"=>$errors[0]], 200);
        }
        Configs::where('key','mail.from.name')->update(['value' => $request->mail_name]);
        Configs::where('key','mail.from.address')->update(['value' => $request->mail_address]);
        Configs::where('key','mail.default')->update(['value' => $request->mail_driver]);
        Configs::where('key','mail.mailers.smtp.host')->update(['value' => $request->mail_host]);
        Configs::where('key','mail.mailers.smtp.port')->update(['value' => $request->mail_port]);
        Configs::where('key','mail.mailers.smtp.username')->update(['value' => $request->mail_username]);
        Configs::where('key','mail.mailers.smtp.password')->update(['value' => $request->mail_password]);
        Configs::where('key','mail.mailers.smtp.encryption')->update(['value' => $request->mail_encryption]);
        
        return response()->json(["status"=>"success","message"=>'Update was successful!'], 200);
    }
}

app/Http/Controllers/Backend/MasterCategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\MasterCategory;
use Illuminate\Support\Facades\Validator;

class MasterCategoryController extends Controller
{

    public function index(Request $request)
    {
        $keyword = $request->get('search');
        $perPage = 25;

        if (!empty($keyword)) {
            $collection = MasterCategory::where('name', 'LIKE', "%$keyword%")
                ->paginate($perPage);
        } else {
            $collection = MasterCategory::paginate($perPage);
        }
        
        return view('backend.master-category.index', compact('collection'));
    }

    public function store(Request $request)
    {
        $rules =array(
            'name' => 'required|unique:master_categories,name',
        );
        $validator=Validator::make($request->all(),$rules);
        if($validator->fails())
        {
            $messages=$validator->messages();
            $errors=$messages->all();
            return response()->json(["status"=>"error","message"=>$errors[0]], 200);
        }

        MasterCategory::create([
            'name' => $request->name,
        ]);
        return response()->json(["status"=>"success","message"=>'Category added!'], 200);
    
    }
    public function update(Request $request)
    {
       
        $rules =array(
            'name' => 'required|unique:master_categories,name,' .$request->name,
        );
        
        $validator=Validator::make($request->all(),$rules);
        
        if($validator->fails())
        {
            $messages=$validator->messages();
            $errors=$messages->all();
            return response()->json(["status"=>"error","message"=>$errors[0]], 200);
        }

        $requestData = $request->all();
        $collection = MasterCategory::findOrFail($request->id);
        $collection->update($requestData);
        return response()->json(["status"=>"success","message"=>'Category updated!'], 200);
    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return void
     */
    public function destroy($id)
    {
        MasterCategory::destroy($id);
        return response()->json(["status"=>"success","message"=>'Category deleted!'], 200);
    }
    


}

app/Http/Controllers/Backend/MasterCountryCodeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\MasterCountryCode;
use Illuminate\Support\Facades\Validator;

class MasterCountryCodeController extends Controller
{
    public function index(Request $request)
    {
        $keyword = $request->get('search');
        $table_name = "Country Code Table";
        $table_information = "Master Country Code Table";
        $perPage = 25;

        if (!empty($keyword)) {
            $collection = MasterCountryCode::where('name', 'LIKE', "%$keyword%")->paginate($perPage);
        } else {
            $collection = MasterCountryCode::paginate($perPage);
        }

        return view('backend.master-country-code.index', compact('collection','table_name','table_information'));
    }

    public function store(Request $request)
    {
        $rules =array(
            'name' => 'required|unique:master_country_codes,name',
        );
        $validator=Validator::make($request->all(),$rules);
        if($validator->fails())
        {
            $messages=$validator->messages();
            $errors=$messages->all();
            return response()->json(["status"=>"error","message"=>$errors[0]], 200);
        }

        MasterCountryCode::create([
            'name' => $request->name,
        ]);
        return response()->json(["status"=>"success","message"=>'Country Code added!'], 200);
    
    }
    public function update(Request $request)
    {
        $rules =array(
            'name' => 'required|unique:master_country_codes,name,' .$request->name,
        );
        
        $validator=Validator::make($request->all(),$rules);
        
        if($validator->fails())
        {
            $messages=$validator->messages();
            $errors=$messages->all();
            return response()->json(["status"=>"error","message"=>$errors[0]], 200);
        }
        $requestData = $request->all();
        $collection = MasterCountryCode::findOrFail($requestData['id']);
        $collection->update($requestData);
        return response()->json(["status"=>"success","message"=>'Country Code updated!'], 200);
    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return void
     */
    public function destroy($id)
    {
        MasterCountryCode::destroy($id);
        return response()->json(["status"=>"success","message"=>'Country Code deleted!'], 200);
    }
}

resources/views/backend/roles/create.blade.php
@extends('layouts.app')
@section('content')
<div class="contents">
   <div class="container-fluid">
      <div class="row">
         <div class="col-lg-12">
            <div class="d-flex align-items-center user-member__title mb-30 mt-30">
               <h4 class="text-capitalize">add Role</h4>
            </div>
         </div>
      </div>
      <div class="card mb-50">
         <div class="row justify-content-center">
            <div class="col-sm-5 col-10">
               <div class="mt-40 mb-50">
                  <div class="edit-profile__body">
                  
                     @if ($errors->any())
                           <ul class="alert alert-danger">
                              @foreach ($errors->all() as $error)
                                 <li>{{ $error }}</li>
                              @endforeach
                           </ul>
                     @endif

                 {!! Form::open(['url' => '/admin/roles', 'class' => 'form-horizontal']) !!}

                 @include ('backend.roles.form', ['formMode' => 'create'])

                 {!! Form::close() !!}
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
@endsection

resources/views/backend/roles/delete.blade.php
 <!-- ends: .modal-info-warning -->
 <div class="modal-info-confirmed modal fade show" id="modal-info-confirmed" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-info" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="modal-info-body d-flex">
                    <div class="modal-info-icon warning">
                        <span data-feather="info"></span>
                    </div>
                    <div class="modal-info-text">
                        <h6>Do you Want to delete these items?</h6>
                        <p>Some descriptions</p>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
            <input type="hidden" name="id" id="id">
                <button type="button" class="btn btn-light btn-outlined btn-sm" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-danger btn-sm" onclick="destroy()">Delete</button>
            </div>
        </div>
    </div>
</div>
<!-- ends: .modal-info-confirmed -->
<script>

    function remove(id){
        $('#id').val(id);
    }

    function destroy(){
        var id =$('#id').val();
        createOverlay("process...");
        $.ajax({
            type: 'POST',
            dataType: 'json',
            data: {
                '_token' : '{{ csrf_token() }}',
                _method: 'DELETE',
                id: id,
            },
            url: "/admin/roles/"+id,
            success: function(data){
                gOverlay.hide();

                if(data["status"] == "success") {            
                    toastr.success(data["message"]);
                    setTimeout(function(){ 
                        window.location = "{{ route('roles.index') }}";
                    }, 500);            
                }else {
                    toastr.error(data["message"]);
                }
            },
            error: function(error) {
                alert("Server/network error\r\n" + error);
            }
        });
    }


</script>

resources/views/backend/roles/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="contents">
   <div class="container-fluid">
      <div class="row">
         <div class="col-lg-12">
            <div class="d-flex align-items-center user-member__title mb-30 mt-30">
               <h4 class="text-capitalize">add Role</h4>
            </div>
         </div>
      </div>
      <div class="card mb-50">
         <div class="row justify-content-center">
            <div class="col-sm-5 col-10">
               <div class="mt-40 mb-50">
                  <div class="edit-profile__body">
                    
                     @if ($errors->any())
                     <ul class="alert alert-danger">
                         @foreach ($errors->all() as $error)
                             <li>{{ $error }}</li>
                         @endforeach
                     </ul>
                 @endif
                    {!! Form::model($role, [
                        'method' => 'PATCH',
                        'url' => ['/admin/roles', $role->id],
                        'class' => 'form-horizontal'
                    ]) !!}

                    @include ('backend.roles.form', ['formMode' => 'edit'])

                    {!! Form::close() !!}
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
@endsection

resources/views/backend/roles/form.blade.php
<div class="form-group{{ $errors->has('name') ? ' has-error' : ''}}">
    {!! Form::label('name', 'Name: ', ['class' => 'control-label']) !!}
    {!! Form::text('name', null, ['class' => 'form-control', 'required' => 'required']) !!}
    {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group {{ $errors->has('permission') ? 'has-error' : ''}}">
    {!! Form::label('permission', 'Permission', ['class' => 'control-label']) !!}
    @if(count($permissions) > 0)
        @foreach($permissions as $key => $value)
        <br>
            <label>{!! Form::checkbox('permission[]', $key,  isset($role->id) ?  in_array($key, $rolePermissions) ? true : null : null,array('class' => 'name')) !!} {{ $value }}</label>
        
            @endforeach
        {!! $errors->first('permission', '<p class="help-block">:message</p>') !!}
    @else
        <p>There are no permission options, make it first ...!</p>
    @endif
</div>
<div class="button-group d-flex pt-25 justify-content-end">

    {!! Form::submit($formMode === 'edit' ? 'Update' : 'Create', ['class' => 'btn btn-primary btn-default btn-squared text-capitalize radius-md shadow2 btn-sm']) !!}

 </div>

resources/views/backend/roles/index.blade.php
@extends('layouts.app')
@section('content')
<div class="contents">
    <div class="container-fluid">
       <div class="row">
          <div class="col-lg-12">
             <div class="contact-breadcrumb">
                <div class="breadcrumb-main add-contact justify-content-sm-between ">
                   <div class=" d-flex flex-wrap justify-content-center breadcrumb-main__wrapper">
                      <div class="d-flex align-items-center add-contact__title justify-content-center mr-sm-25">
                         <h4 class="text-capitalize fw-500 breadcrumb-title">List Roles</h4>
                         <span class="sub-title ml-sm-25 pl-sm-25"></span>
                      </div>
                      <div class="action-btn mt-sm-0 mt-15">
                            @can ('roles-create')
                                <a href="{{ url('/admin/roles/create') }}" class="btn btn-primary btn-sm"><i class="las la-plus fs-16"></i>Add New</a>
                            @endcan
                        </div>
                   </div>
                   <div class="breadcrumb-main__wrapper">
                      <form action="{{ url('/admin/roles') }}" method="GET" class="d-flex align-items-center add-contact__form my-sm-0 my-2">
                         <span data-feather="search"></span>
                         <input class="form-control mr-sm-2 border-0 box-shadow-none" name="search" value="{{ request('search') }}" type="search" id="userName" onkeyup="userFunction()" placeholder="Search by Role Name" aria-label="Search">
                      </form>
                   </div>
                </div>
             </div>
             <!-- ends: contact-breadcrumb -->
          </div>
       </div>
       <div class="row">
          <div class="col-lg-12 mb-30">
             <div class="card">
                <div class="card-header color-dark fw-500">
                 View List
                </div>
                <div class="card-body">
                   <div class="userDatatable global-shadow border-0 bg-white w-100">
                     @include('layouts.partials._message')
                     <div class="row ">
                        <div class="col">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr class="userDatatable-header">
                                        <th>
                                           <span class="userDatatable-title">Role</span>
                                        </th>
                                        <th>
                                           <span class="userDatatable-title">Permissions</span>
                                        </th>
                                       <th>
                                          <span class="userDatatable-title">Number of Users</span>
                                       </th>
                                       <th>
                                          <span class="userDatatable-title">Actions</span>
                                       </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($roles as $item)
                                        <tr>
                                            <td>{{ ucwords($item->name) }}</td>
                                            <td>
                                                @if($item->id == 1)
                                                    All
                                                @else
                                                    @if($item->permissions->count())
                                                        @foreach($item->permissions as $permission)
                                                            {{ ucwords($permission->name) }}
                                                        @endforeach
                                                    @else
                                                        None
                                                    @endif
                                                @endif
                                            </td>
                                            
                                            <td>{{ $item->users->count() }}</td>
                                            
                                            @canany(['roles-edit','roles-delete'])
                                                <td>
                                                    @if($item->id == 1)
                                                         N/A
                                                    @else
                                                        <ul class="mb-0 d-flex flex-wrap">
                                                            @can ('roles-edit')
                                                                <li>
                                                                    <a href="{{ url('/admin/roles/' . $item->id . '/edit') }}" title="Edit Role"><button class="btn btn-icon btn-circle btn-outline-light btn-sm"><span data-feather="edit"></span></button></a>
                                                                </li>
                                                            @endcan
                                                            @can ('roles-delete')
                                                                <li>
                                                
                                                                    <button type="button" onClick="remove({{ $item->id}})" class="btn btn-icon btn-circle btn-outline-light btn-sm" data-toggle="modal" data-target="#modal-info-confirmed" > <span data-feather="trash-2"></span></button>
                                                                </li>
                                                            @endcan
                                                            <li>
                                                            </li>
                                                        </ul>
                                                    @endif
                                                    </div>
                                                </td>
                                            @endcanany
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div><!--col-->
                    </div><!--row-->
                    <div class="row">
                        <div class="col-7">
                            <div class="float-left">
                                {!! $roles->total() !!} roles total
                            </div>
                        </div><!--col-->
            
                        <div class="col-5">
                            <div class="float-right">
                                {!! $roles->appends(['search' => Request::get('search')])->render() !!}
                            </div>
                        </div><!--col-->
                    </div><!--row-->
                   </div>
                </div>
             </div>
          </div>
       </div>
    </div>
 </div>
 @include('backend.roles.delete')
@endsection